version: "3.8"

services:

  mongo:
    image: mongo
    restart: always

  cid-checker-frontend:
    image: cid-checker-frontend
    restart: always
    ports:
      - 8080:8080

  cid-checker-backend:
    image: cid-checker
    restart: always
    environment:
      - CID_LOTUS_RPCURL=ws://3.9.46.104:1234/rpc/v0
      - CID_DB_CONNECTIONSTRING=mongodb://mongo:27017

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data


volumes:
  caddy_data: